/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cheonkyu;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import io.cheonkyu.service.CommentService;

public class Main {
    public static void main(String[] args) {
        var context = new AnnotationConfigApplicationContext(ProjectConfig.class);

        var service = context.getBean(CommentService.class);
        Comment comment = new Comment();
        comment.setText("텍스트");
        comment.setAuthor("글쓴이");

        service.publishComment(comment);
    }
}
