/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cheonkyu;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import io.cheonkyu.services.Comment;
import io.cheonkyu.services.CommentService;

public class Main {
    public static void main(String[] args) {
        var context = new AnnotationConfigApplicationContext(ProjectConfig.class);
        var service = context.getBean(CommentService.class);

        Comment comment = new Comment();
        comment.setAuthor("글쓴이");
        comment.setText("텍스트");
        service.publishComment(comment);
    }
}
