/*
 * This source file was generated by the Gradle 'init' task
 */
package io.cheonkyu;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Main {
    public static void main(String[] args) {
        var context = new AnnotationConfigApplicationContext(ProjectConfig.class);

        var cs1 = context.getBean("commentServiceTest", CommentService.class);
        var cs2 = context.getBean("commentServiceTest", CommentService.class);
        System.out.println("프로토타입 빈은 요청할 때마다 새로운 인스턴스를 생성하기에 false");
        System.out.println(cs1 == cs2);

        var cs = context.getBean(CommentService.class);
        cs.sendComment();
        cs.sendComment();
    }
}
